### ISSUE TITLE
cant run image (error odoo.egg-info)

### ISSUE THREAD

**Issue by flocalhost** [camptocamp/docker-odoo-project#114]
i cant find out where the problem is, but after creating the image for odoo 12 and running it in my docker-compose (customized the one from example folder) i get the following error message:

`Starting with UID : 999

Running without demo data
/odoo/src/odoo.egg-info is missing, probably because the directory is a volume.
Running pip install -e /odoo/src to restore odoo.egg-info
ERROR: /odoo/src is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with svn+, git+, hg+, or bzr+).
`

**Comment by simahawk** [comment]
`odoo/src` must contain the odoo source. In our projects w/ add it via submodule.

**Comment by hoang-innomizetech** [comment]
I am getting the same issue when running Odoo on AWS ECS Fargate that mounted the _/odoo_ dir to our EFS. We used this [Dockerfile](https://github.com/camptocamp/docker-odoo-project/blob/master/example/odoo/Dockerfile) and the Odoo src is copied from our local to docker.

@simahawk Based on your experience, what are other root reasons that can cause this error i.e. permission?

**Comment by simahawk** [comment]
permissons? bad path? bad volume? What do you get on `docker build odoo`?

**Comment by hoang-innomizetech** [comment]
We have fixed the above issue. The mouth path for Odoo data dir should be _/data/odoo_ but we accidentally set to _/odoo_ directory
