### ISSUE TITLE
Debian roadmap

### ISSUE THREAD

**Issue by hparfr** [camptocamp/docker-odoo-project#118]
Hi folks,

The end of LTS of Debian Jessie is 30/6/2020.
Odoo v8 and v9 are currently based on Jessie.

Are you planning to upgrade it to Debian Stretch ?

**Comment by guewen** [comment]
There was an attempt: https://github.com/camptocamp/docker-odoo-project/pull/33

**Comment by yvaucher** [comment]
Hi @hparfr 

For you to know we also have Odoo 10.0 using jessie.
the aim was initially to follow Odoo recommendations to have the supported version of debian.

We update the base images when there are security updates.
So until 2020-06-30 we will probably stick to the Jessie version unless known security issues have arised or if Odoo changed their supported version (which might not occurs for old versions).

We based our decision to stick on jessie on sle-odoo comment here:
https://github.com/odoo/odoo/issues/15308#issuecomment-276934340

Worth mentioning, last time we tried to upgrade the debian version we had dependencies errors. Thus we have been considering it as unstable. Here was our attempt for version 10.0
https://github.com/camptocamp/docker-odoo-project/pull/33
With errors on wkhtml2pdf
https://travis-ci.org/camptocamp/docker-odoo-project/jobs/273270494#L1871

But, we are open to suggestions, why would you like to use Stretch?
An option could be to do a separate build based on Stretch.

**Comment by hparfr** [comment]
Thanks.

The probability to still have old project in old versions of Odoo next year is very high for us. 
I do not know if it's better to put the effort on migrating Debian or to do something else (like limit web exposure).

I didn't try to migrate to Stretch yet, but based on your issues about wkhtml2pdf, may be this is the solution : https://stackoverflow.com/questions/38262173/how-to-correctly-install-wkhtmltopdf-on-debian-64-bit#answer-55324202 or this one http://zeroheure.info/how-to-install-odoo-on-latest-debian-ubuntu-without-python-pypdf-dependency/
