### ISSUE TITLE
Cannot make submodule

### ISSUE THREAD

**Issue by yymphoo96** [camptocamp/docker-odoo-project#133]
git submodule add git@github.com:odoo/odoo.git odoo/src

> Cloning into '/home/frontiir/odoo/src'...
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> fatal: clone of 'git@github.com:odoo/odoo.git' into submodule path '/home/frontiir/odoo/src' failed

**Comment by guewen** [comment]
Hello, it seems you didn't configure your ssh key on GitHub. Have a look at https://help.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh
Unrelated to this project though.
