### ISSUE TITLE
How can i build my image without nginx and postgresql ? 

### ISSUE THREAD

**Issue by esakarya** [camptocamp/docker-odoo-project#199]
I want use postgresql and nginx outside docker how can i my image without them ?

**Comment by yvaucher** [comment]
For postgresql, you can simply change the DB_* env var.

 https://github.com/camptocamp/docker-odoo-project/blob/master/example/docker-compose.yml#L20-L22
(You also have DB_HOST available, see the full list here: https://github.com/camptocamp/docker-odoo-project/blob/master/15.0/templates/odoo.cfg.tmpl#L5-L8

To replace nginx, you will have to configure your alternative like traefik. Know that the container will work without any reverse proxy but you will loose the long polling.

**Comment by esakarya** [comment]
i will try nginx with nginx ingress,
and i am try adapt this for kubernetes
