### ISSUE TITLE
remote postgresql user/database connection issue

### ISSUE THREAD

**Issue by karthik1710** [camptocamp/docker-odoo-project#218]
Hi,
Im trying to setup docker compose stack, odoo with  remote db instead of stack db.
Whenever i try to start the container, it throws error password authentication failed,
```bash
Starting with UID : 999
Running without demo data
2022/09/28 15:41:47 Waiting for: tcp://192.168.1.104:5432
2022/09/28 15:41:47 Connected to tcp://192.168.1.104:5432
psql: error: connection to server at "192.168.1.104", port 5432 failed: FATAL:  password authentication failed for user "odoo-c2c"
createdb: error: connection to server at "192.168.1.104", port 5432 failed: FATAL:  password authentication failed for user "odoo-c2c"
```
But when i use stack db it working. As well as when I use remote db with odoo stock image, it works perfectly.
Im not user what is the problem causing. remote db is accessible is accessible over the network. Password is also correct, but it throws password authentication failed. Thanks

**Comment by gurneyalex** [comment]
you need to configure the access on your postgresql remote server in the file pg_hba.conf 

See https://www.postgresql.org/docs/current/auth-pg-hba-conf.html
