### ISSUE TITLE
Error pytest

### ISSUE THREAD

**Issue by TDu** [camptocamp/docker-odoo-project#49]
After upgrading a project to the last version
The following error occur when running pytest
```
Plugin 'pytest_cov' could not be loaded: (six 1.9.0 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('six>=1.10.0'))
```

**Comment by yvaucher** [comment]
Ok this is strange, six seems to be a dependency of the tests in pytest-cov not more.

https://github.com/pytest-dev/pytest-cov/blob/master/tox.ini#L33
https://github.com/pytest-dev/pytest-cov/blob/master/tests/test_pytest_cov.py#L15

Seems that pytest use its six dependency only for testing. pytest_cov seems to follow the last version of six.

Thus the fix could be to either to fix the version of pytest_cov to 2.4.0 or to let loose the version of six.

By the way this dependency was updated a long time ago on Odoo v10:
https://github.com/odoo/odoo/commit/56d7bf1f46904ed5d92e91559a6b360bf697b003

I just fear that updating the image will still make pytest-cov complaining it want's the last one.
Well I give it a shot.
